import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';
import 'package:shared_preferences/shared_preferences.dart';
// ignore: unused_import
import 'di_module.dart'; // Required for injectable_generator to see the module
import 'injection.config.dart';

final getIt = GetIt.instance;

@InjectableInit()
Future<void> configureDependencies() async {
  // Initialize SharedPreferences manually before getIt.init()
  // This ensures it's available immediately for other dependencies
  // We register it manually here to avoid conflicts with generated code
  final sharedPreferences = await SharedPreferences.getInstance();
  getIt.registerSingleton<SharedPreferences>(sharedPreferences);

  // Initialize injectable dependencies
  // This will be generated by injectable_generator
  // Run: dart run build_runner build --delete-conflicting-outputs
  // Note: The generated code may try to register SharedPreferences again,
  // so we need to ensure it's registered before calling init()
  await getIt.init();
}
