import 'package:freezed_annotation/freezed_annotation.dart';

part 'login_request.freezed.dart';
part 'login_request.g.dart';

@freezed
class LoginRequest with _$LoginRequest {
  const LoginRequest._();
  
  const factory LoginRequest({
    @JsonKey(name: "usernameOrEmail") required String usernameOrEmail,
    required String password,
  }) = _LoginRequest;

  factory LoginRequest.fromJson(Map<String, dynamic> json) =>
      _$LoginRequestFromJson(json);
  
  // toJson will be generated by json_serializable after running: make gen
}
