#!/bin/bash

# Script to help set up iOS flavors in Xcode
# This script provides instructions and opens Xcode

echo "=========================================="
echo "iOS Flavors Setup Helper"
echo "=========================================="
echo ""
echo "This script will help you set up iOS flavors (schemes) in Xcode."
echo ""
echo "Steps:"
echo "1. Xcode will open automatically"
echo "2. Follow the instructions below to create schemes"
echo ""
read -p "Press Enter to continue..."

# Open Xcode workspace
open ios/Runner.xcworkspace

echo ""
echo "=========================================="
echo "Manual Setup Steps:"
echo "=========================================="
echo ""
echo "1. CREATE BUILD CONFIGURATIONS:"
echo "   - Select 'Runner' project → 'Runner' target → 'Info' tab"
echo "   - Under 'Configurations', duplicate:"
echo "     * Debug → Debug-dev"
echo "     * Debug → Debug-stg"
echo "     * Release → Release-dev"
echo "     * Release → Release-stg"
echo ""
echo "2. CREATE SCHEMES:"
echo "   - Go to Product → Scheme → Manage Schemes"
echo "   - Click '+' to create:"
echo "     * 'dev' scheme (uses Debug-dev/Release-dev)"
echo "     * 'stg' scheme (uses Debug-stg/Release-stg)"
echo "     * 'prod' scheme (uses Debug/Release)"
echo ""
echo "3. ADD SWIFT FLAGS:"
echo "   - Select Runner target → Build Settings"
echo "   - Search for 'Other Swift Flags'"
echo "   - Add for each configuration:"
echo "     * Debug-dev: -D DEV"
echo "     * Debug-stg: -D STG"
echo "     * Release-dev: -D DEV"
echo "     * Release-stg: -D STG"
echo "     * Debug (prod): -D PROD"
echo "     * Release (prod): -D PROD"
echo ""
echo "4. UPDATE BUNDLE IDENTIFIERS (Optional):"
echo "   - In Build Settings, search for 'Product Bundle Identifier'"
echo "   - Set:"
echo "     * Dev: com.example.personal_finance.dev"
echo "     * Stg: com.example.personal_finance.stg"
echo "     * Prod: com.example.personal_finance"
echo ""
echo "=========================================="
echo "After setup, you can use:"
echo "  make run-dev    # Run dev flavor"
echo "  make run-stg    # Run staging flavor"
echo "  make run-prod   # Run production flavor"
echo "=========================================="
